### PR TITLE
Update to 0.39.1

### PR DESCRIPTION
**Pull request by AndrewVallette**
## Changes
Updated version to 0.39.1
Updated `home_url` and `doc_url`
Added `license_family`
Removed unused patches

## Notes
The `home_url` (`https://llvmlite.pydata.org`) is currently being redirected to `readthedocs.io`. It seems that the `llvmlite.pydata.org` should be considered the canonical URL, and is specified as the home URL on the GitHub page.

### CODE REVIEW

**Review by varlackc — COMMENTED** [review]
There seems to be a redirect in the `home url`

**Comment by AndrewVallette** [comment]
> There seems to be a redirect in the `home url`

Hm yeah I noticed that, but I am not sure which I want to use. Could you comment on my note above? To me, `llvmlite.pydata.org` seems more like the proper home of the project instead of `readthedocs.io`.. and it is used in their github, too. what do you think?

**Review by varlackc — COMMENTED** [review]
I think that we could leave it as it is for now but in the future we probably should keep an eye on it.

**Review by varlackc — APPROVED** [review]
LGTM

**Review by ScottBailey — APPROVED** [review]
My only comment is this: I prefer to replace make with ninja; however, there is NO reason to hold this review up for a personal preference.

**Review by cbouss — APPROVED** [review]
LGTM

**Comment by AndrewVallette** [comment]
> My only comment is this: I prefer to replace make with ninja; however, there is NO reason to hold this review up for a personal preference.

Thank you Scott. I think 0.40 is out now, so I can revisit this with the next build :)

**Pull request merged**
